### ISSUE TITLE
Average Volume(3M) not available

### ISSUE THREAD

**Issue by Jammooly1** [felipeoriani/Fynance#14]
Hello, is it possible to add the Average Volume (3M) for a stock indicator or quote? 

Also, is it possible to just add all the advanced stats of a stock quote that one can view at other yahoo finance APIs as well?

Thank you

**Comment by felipeoriani** [comment]
No, the idea here is just to provide the historical stock data. You can find good and public packages to calculate technical indicators using the data provided by Fynance.
