### ISSUE TITLE
Fynance.FynanceException: 'Fynance.Yahoo: This result was not possible to get from Yahoo Finance.'

### ISSUE THREAD

**Issue by ElDuderinoBerlin** [felipeoriani/Fynance#19]
var result = await Ticker.Build()
                         .SetSymbol("MSFT")
                         .SetPeriod(Fynance.Period.OneMonth)
                         .SetStartDate(DateTime.Now.AddDays(-365))
                         .SetFinishDate(DateTime.Now)
                         .GetAsync();

foreach (var item in result.Quotes)
{
    Console.WriteLine($"Date: {item.Period}, Close: {item.Close}");
}

**Comment by rubby-c** [comment]
Did you figure it out?
