### ISSUE TITLE
Started throwing an exception today! 

### ISSUE THREAD

**Issue by atsmark** [felipeoriani/Fynance#20]
Good evening,
I have a C# app using your worderful wrapper for Yahoo Finance. This afternoon, I noticed it was throwing an exception;

Fynance.FynanceException: Fynance.Yahoo: This result was not possible to get from Yahoo Finance.

This is a sample of my call - the strTicker = "SPY"
            var result = await Ticker.Build()
                          .SetSymbol(strTicker)
                          .SetTimeZone(TimeZoneInfo.Local)
                          .SetPeriod(Period.OneYear)
                          .SetInterval(Interval.OneDay)
                          .GetAsync();

The resulting URL I see in your code is

https://query1.finance.yahoo.com/v8/finance/chart/SPY?range=1y&interval=1d

This URL works fine from a browser...

Any ideas?
Thanks for the great work! 
Mark

**Comment by felipeoriani** [comment]
Hi @atsmark, thanks for opening this issue. I haven´t look into this package from a long time but I can try to take a look soon. I will update a new version in case I find any particular issue, but please, since you´re using it, feel free to open a PR into this repo to contribute on it as well.

Thank you!

**Comment by atsmark** [comment]
Felipe, thanks for getting back.  I will attempt to open a pull request and take a look.


Thanks,

Mark



________________________________

**Comment by atsmark** [comment]
Felipe, I'm new to GitHub and don't want to muck up your project...  So I downloaded a zip and ran the Test you provided.  Here is what fixed most of it.

YahooTickers.cs starting at line 114

            /// <summary>
            /// Get a http response message from the client instance.
            /// </summary>
            /// <param name="url">Url to invoke.</param>
            /// <returns>An instance of HttpResponseMessage.</returns>
            private async Task<HttpResponseMessage> GetResponse(string url)
            {
                  if (Client == null)
                  {
                        Client = new HttpClient(new HttpClientHandler { UseProxy = false })

                                                           //MJM May 31 2024 - Needs something in the user-agent or fails...                         <<<  I added
                                                           Client.DefaultRequestHeaders.Add("User-Agent", "C# App");                                  <<<  I added
                                         }

                  return await Client.GetAsync(url).ConfigureAwait(false);
            }

This fixes all tests except Splits and Dividends?  I will keep working on it!


Thanks,

Mark



________________________________

**Comment by felipeoriani** [comment]
Hi @atsmark, I don´t know how familiar you are with git, but usually we create a fork of the repository, push our changes and open a pull request into the original repository. I will take a look soon as this weekend and add some extra methods if we need.

Did you identify if adding the `user-agent` on the request header solves the issue?

Also, which exactly version of the package are you using?

Please, let me know if you find potential fixes and I can do it.

**Comment by atsmark** [comment]
Felipe,
I am not familiar with GitHub!

Yes, the "user-agent" addition fixes most of the problems and indeed allows for normal operation until you ask for Splits or Dividends.

I have never run the Tests before and I don't user either Splits or Dividends so I don't know if these two where working before yesterday.

Before change
[cid:02b89e13-c3ca-49a0-928a-3042532a3bc1]

After change
[cid:9a88d62c-4ad7-44ce-9ea6-0fb2d00a623c]


Thanks,

Mark



________________________________

**Comment by atsmark** [comment]
Felipe,

Upon further looking, the symbol in the TESTs for dividend and splits had been delisted (or no longer available on Yahoo).  I used ADP for stock, splits and dividends and not ALL tests are working.

So the user-agent addition (and changing stock symbols) allows all TESTs to run with success.


Thanks,

Mark



________________________________

**Comment by felipeoriani** [comment]
Hi Mark,

I've just released the version `1.2.0`, please, update your package on your code.

You can check details here https://www.nuget.org/packages/Fynance/1.2.0

I am planning to start a new version soon by doing some improvements regarding package version. 

And please, let me know if it solves the problem for you and we can close this issue.

Thanks for catching this.

Note: Recently I've received some notifications from paypal about a donate, I don't know if it was you but you've tried to donate something, please retry again if you want, I've fixed my account.

**Comment by atsmark** [comment]
Felipe,

Yes, v1.2.0 fixed the problem completely!

Thank you very much.


Thanks,

Mark



________________________________
